<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace Cls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cls.Log</code>
 */
class Log extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 time = 1;</code>
     */
    protected $time = 0;
    /**
     * Generated from protobuf field <code>repeated .cls.Log.Content contents = 2;</code>
     */
    private $contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $time
     *     @type \Cls\Log\Content[]|\Google\Protobuf\Internal\RepeatedField $contents
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cls::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 time = 1;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     * Generated from protobuf field <code>int64 time = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .cls.Log.Content contents = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContents()
    {
        return $this->contents;
    }

    /**
     * Generated from protobuf field <code>repeated .cls.Log.Content contents = 2;</code>
     * @param \Cls\Log\Content[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Cls\Log\Content::class);
        $this->contents = $arr;

        return $this;
    }

}

