<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace Cls;

if (false) {
    /**
     * This class is deprecated. Use Cls\Log\Content instead.
     * @deprecated
     */
    class Log_Content {}
}
class_exists(Log\Content::class);
@trigger_error('Cls\Log_Content is deprecated and will be removed in the next major release. Use Cls\Log\Content instead', E_USER_DEPRECATED);

